// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykigacghgqfciyuaylvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlraWdhY2doZ3FmY2l5dWF5bHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTkyNjEsImV4cCI6MjA3MjM3NTI2MX0.K4XMmA8bR483ZMxYn-tWx9R_Y-lwaSxSugvDWg6TjVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});